function groups = algorithm_groups()
% algorithm_groups
% Group BBO variants by lifecycle stage for reproducible research management.

    groups = struct();

    groups.stable = {
        'BBO_improved_v3.m', ...
        'BBO_improved_v4.m', ...
        'BBO_v3_baseline.m'};

    groups.ablation = {
        'BBO_improved_v3_ablation_core.m', ...
        'BBO_v3_dir_small_step.m', ...
        'BBO_v3_dir_small_step_late_local_refine.m', ...
        'BBO_v3_dir_small_step_gate_late_local_refine.m', ...
        'BBO_v3_dir_stag_only.m', ...
        'BBO_v3_dir_stag_bottom_half.m', ...
        'BBO_v3_dir_stag_bottom_half_late_refine.m', ...
        'BBO_v3_dir_clipped_stag_bottom_half_late_refine.m'};

    groups.deprecated = {
        'BBO_improved_v1.m', ...
        'BBO_improved_v2.m'};
end
