function [best_fitness, best_solution, Convergence_curve] = BBO_route_b_state_driven_bbo(N, Max_iteration, lb, ub, dim, fobj)
% BBO_route_b_state_driven_bbo
% Route B minimal prototype:
% three-state GDP schedule (early/mid/late), no SEL/ESC.

    runtime_cfg = struct( ...
        'mode', 'v1_full', ...
        'enable_selective_elite_learning', false, ...
        'enable_gated_directional_push', true, ...
        'enable_anti_stagnation_escape', false, ...
        'state_driven_enabled', true, ...
        'state_phase_1', 0.33, ...
        'state_phase_2', 0.67, ...
        'state_early_step_scale', 0.65, ...
        'state_mid_step_scale', 1.00, ...
        'state_late_step_scale', 1.25, ...
        'state_early_noise_scale', 1.10, ...
        'state_mid_noise_scale', 1.00, ...
        'state_late_noise_scale', 0.75, ...
        'gdp_start_progress', 0.20, ...
        'gdp_target_ratio', 0.22);

    [best_fitness, best_solution, Convergence_curve] = run_v1_with_runtime_cfg( ...
        runtime_cfg, N, Max_iteration, lb, ub, dim, fobj);
end

function [best_fitness, best_solution, Convergence_curve] = run_v1_with_runtime_cfg(runtime_cfg, N, Max_iteration, lb, ub, dim, fobj)
    old_exists = isappdata(0, 'BBO_V1_RUNTIME_CFG');
    if old_exists
        old_cfg = getappdata(0, 'BBO_V1_RUNTIME_CFG');
    else
        old_cfg = [];
    end

    setappdata(0, 'BBO_V1_RUNTIME_CFG', runtime_cfg);
    cleanup_obj = onCleanup(@() restore_runtime_cfg(old_exists, old_cfg)); %#ok<NASGU>

    [best_fitness, best_solution, Convergence_curve] = BBO_improved_v1(N, Max_iteration, lb, ub, dim, fobj);
end

function restore_runtime_cfg(old_exists, old_cfg)
    if old_exists
        setappdata(0, 'BBO_V1_RUNTIME_CFG', old_cfg);
    else
        if isappdata(0, 'BBO_V1_RUNTIME_CFG')
            rmappdata(0, 'BBO_V1_RUNTIME_CFG');
        end
    end
end
